const airports = [
  {
    city: "New Delhi",
    state: "Delhi",
    airport_name: "Indira Gandhi International Airport",
    code: "DEL",
  },
  {
    city: "Lucknow",
    state: "Uttar Pradesh",
    airport_name: "Chaudhary Charan Singh International Airport",
    code: "LKO",
  },
  {
    city: "Varanasi",
    state: "Uttar Pradesh",
    airport_name: "Lal Bahadur Shastri International Airport",
    code: "VNS",
  },
  {
    city: "Kushinagar",
    state: "Uttar Pradesh",
    airport_name: "Kushinagar Airport",
    code: "KNU",
  },
  {
    city: "Jewar",
    state: "Uttar Pradesh",
    airport_name: "Noida International Airport",
    code: "NIA",
  },
  {
    city: "Mumbai",
    state: "Maharashtra",
    airport_name: "Chhatrapati Shivaji International Airport",
    code: "BOM",
  },
  {
    city: "Nagpur",
    state: "Maharashtra",
    airport_name: "Dr. Babasaheb Ambedkar International Airport",
    code: "NAG",
  },
  {
    city: "Ahmedabad",
    state: "Gujarat",
    airport_name: "Sardar Vallabhbhai Patel International Airport",
    code: "AMD",
  },
  {
    city: "Surat",
    state: "Gujarat",
    airport_name: "Surat International Airport",
    code: "STV",
  },
  {
    city: "Vadodara",
    state: "Gujarat",
    airport_name: "Vadodara International Airport",
    code: "BDQ",
  },
  {
    city: "Chennai",
    state: "Tamil Nadu",
    airport_name: "Chennai International Airport",
    code: "MAA",
  },
  {
    city: "Coimbatore",
    state: "Tamil Nadu",
    airport_name: "Coimbatore International Airport",
    code: "CJB",
  },
  {
    city: "Tiruchirapalli",
    state: "Tamil Nadu",
    airport_name: "Tiruchirapalli International Airport",
    code: "TRZ",
  },
  {
    city: "Kochi",
    state: "Kerala",
    airport_name: "Cochin International Airport",
    code: "COK",
  },
  {
    city: "Kozhikode",
    state: "Kerala",
    airport_name: "Calicut International Airport",
    code: "CCJ",
  },
  {
    city: "Thiruvananthapuram",
    state: "Kerala",
    airport_name: "Trivandrum International Airport",
    code: "TRV",
  },
  {
    city: "Kannur",
    state: "Kerala",
    airport_name: "Kannur International Airport",
    code: "CNN",
  },
  {
    city: "Gaya",
    state: "Bihar",
    airport_name: "Gaya Airport",
    code: "GAY",
  },
  {
    city: "Jaipur",
    state: "Rajasthan",
    airport_name: "Jaipur International Airport",
    code: "JAI",
  },
  {
    city: "Kolkata",
    state: "West Bengal",
    airport_name: "Netaji Subhash Chandra Bose International Airport",
    code: "CCU",
  },
  {
    city: "Siliguri",
    state: "West Bengal",
    airport_name: "Bagdogra Airport",
    code: "IXB",
  },
  {
    city: "Amritsar",
    state: "Punjab",
    airport_name: "Sri Guru Ram Dass Jee International Airport",
    code: "ATQ",
  },
  {
    city: "Bengaluru",
    state: "Karnataka",
    airport_name: "Kempegowda International Airport",
    code: "BLR",
  },
  {
    city: "Mangalore",
    state: "Karnataka",
    airport_name: "Mangalore International Airport",
    code: "IXE",
  },
  {
    city: "Port Blair",
    state: "Andaman and Nicobar Islands",
    airport_name: "Veer Savarkar International Airport",
    code: "IXZ",
  },
  {
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    airport_name: "Visakhapatnam Airport",
    code: "VTZ",
  },
  {
    city: "Hyderabad",
    state: "Telangana",
    airport_name: "Rajiv Gandhi International Airport",
    code: "HYD",
  },
  {
    city: "Guwahati",
    state: "Assam",
    airport_name: "Lokpriya Gopinath Bordoloi International Airport",
    code: "GAU",
  },
  {
    city: "Goa",
    state: "Goa",
    airport_name: "Dabolim Airport (Goa International Airport)",
    code: "GOI",
  },
  {
    city: "Imphal",
    state: "Manipur",
    airport_name: "Tulihal Airport",
    code: "IMF",
  },
  {
    city: "Bhubaneswar",
    state: "Odisha",
    airport_name: "Biju Patnaik International Airport",
    code: "BBI",
  },
  {
    city: "Srinagar",
    state: "Jammu & Kashmir",
    airport_name: "Sheikh ul-Alam International Airport",
    code: "SXR",
  },
  {
    city: "Ranchi",
    state: "Jharkhand",
    airport_name: "Birsa Munda Airport",
    code: "IXR",
  },
];


export default airports;
