const flightsData = [
  {
    departureTime: "06:30",
    sourceAirport: "DEL",
    arrivalTime: "07:15",
    destinationAirport: "DEL",
    duration: "02h 10m",
    flightNumber: "6E 6218",
    serviceClass: "Economy",
    price: "4974",
    stops: "Non-stop",
  },
  {
    departureTime: "08:45",
    sourceAirport: "LHR",
    arrivalTime: "12:30",
    destinationAirport: "JFK",
    duration: "08h 45m",
    flightNumber: "BA 1234",
    serviceClass: "Business",
    price: "9845",
    rewards: "Earn 410 BA Miles",
    stops: "1 Stop",
  },
  {
    departureTime: "15:00",
    sourceAirport: "DXB",
    arrivalTime: "18:30",
    destinationAirport: "JFK",
    duration: "15h 30m",
    flightNumber: "EK 789",
    serviceClass: "First Class",
    price: "15320",
    rewards: "Earn 720 Skywards Miles",
    stops: "2 Stops",
  },
  {
    departureTime: "10:20",
    sourceAirport: "CDG",
    arrivalTime: "11:45",
    destinationAirport: "FRA",
    duration: "01h 25m",
    flightNumber: "AF 456",
    serviceClass: "Economy",
    price: "1200",
    rewards: "Earn 60 Flying Blue Miles",
    stops: "Non-stop",
  },
  // {
  //   departureTime: "14:10",
  //   sourceAirport: "SFO",
  //   arrivalTime: "18:45",
  //   destinationAirport: "JFK",
  //   duration: "06h 35m",
  //   flightNumber: "DL 567",
  //   serviceClass: "Business",
  //   price: "8,950",
  //   rewards: "Earn 380 Delta SkyMiles",
  //   stops: "1 Stop",
  // },
  // {
  //   departureTime: "19:30",
  //   sourceAirport: "HND",
  //   arrivalTime: "21:45",
  //   destinationAirport: "PEK",
  //   duration: "04h 15m",
  //   flightNumber: "NH 789",
  //   serviceClass: "Economy",
  //   price: "3,550",
  //   rewards: "Earn 180 ANA Mileage Points",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "12:00",
  //   sourceAirport: "MUC",
  //   arrivalTime: "16:30",
  //   destinationAirport: "DXB",
  //   duration: "06h 30m",
  //   flightNumber: "LH 432",
  //   serviceClass: "First Class",
  //   price: "12,750",
  //   rewards: "Earn 620 Miles & More Miles",
  //   stops: "1 Stop",
  // },
  // {
  //   departureTime: "08:00",
  //   sourceAirport: "ATL",
  //   arrivalTime: "12:45",
  //   destinationAirport: "LAX",
  //   duration: "05h 45m",
  //   flightNumber: "DL 123",
  //   serviceClass: "Economy",
  //   price: "5,320",
  //   rewards: "Earn 280 Delta SkyMiles",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "09:15",
  //   sourceAirport: "ORD",
  //   arrivalTime: "11:30",
  //   destinationAirport: "DFW",
  //   duration: "02h 15m",
  //   flightNumber: "AA 789",
  //   serviceClass: "Business",
  //   price: "3,980",
  //   rewards: "Earn 210 AAdvantage Miles",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "16:40",
  //   sourceAirport: "SYD",
  //   arrivalTime: "19:55",
  //   destinationAirport: "MEL",
  //   duration: "03h 15m",
  //   flightNumber: "QF 567",
  //   serviceClass: "Economy",
  //   price: "2,780",
  //   rewards: "Earn 140 Qantas Points",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "11:30",
  //   sourceAirport: "HKG",
  //   arrivalTime: "13:15",
  //   destinationAirport: "TPE",
  //   duration: "01h 45m",
  //   flightNumber: "CX 234",
  //   serviceClass: "Business",
  //   price: "4,560",
  //   rewards: "Earn 240 Asia Miles",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "18:00",
  //   sourceAirport: "LAX",
  //   arrivalTime: "21:30",
  //   destinationAirport: "LHR",
  //   duration: "10h 30m",
  //   flightNumber: "VS 789",
  //   serviceClass: "First Class",
  //   price: "13,980",
  //   rewards: "Earn 660 Flying Club Miles",
  //   stops: "1 Stop",
  // },
  // {
  //   departureTime: "07:45",
  //   sourceAirport: "NRT",
  //   arrivalTime: "10:00",
  //   destinationAirport: "ICN",
  //   duration: "02h 15m",
  //   flightNumber: "KE 789",
  //   serviceClass: "Economy",
  //   price: "2,980",
  //   rewards: "Earn 150 SKYPASS Miles",
  //   stops: "Non-stop",
  // },
  // {
  //   departureTime: "13:00",
  //   sourceAirport: "FRA",
  //   arrivalTime: "15:30",
  //   destinationAirport: "SIN",
  //   duration: "12h 30m",
  //   flightNumber: "SQ 123",
  //   serviceClass: "Business",
  //   price: "10,750",
  //   rewards: "Earn 500 KrisFlyer Miles",
  //   stops: "1 Stop",
  // },
  // {
  //   departureTime: "20:20",
  //   sourceAirport: "AMS",
  //   arrivalTime: "22:45",
  //   destinationAirport: "FCO",
  //   duration: "02h 25m",
  //   flightNumber: "KL 456",
  //   serviceClass: "Economy",
  //   price: "2,350",
  //   rewards: "Earn 120 Flying Dutchman Miles",
  //   stops: "Non-stop",
  // },
];

export default flightsData;
